const content = [
    { title: "All About Us For The Repairing Of Your Car", text: "Welcome to our car workshop, where precision meets passion in every repair. We combine years of hands-on experience with the latest diagnostic tools to ensure your vehicle receives top-notch service. Our mission is to transform car troubles into smooth journeys with expertise and integrity. <br><br>Our team of certified technicians is dedicated to identifying and solving automotive challenges quickly and efficiently. We use only genuine parts and advanced techniques to bring your car back to peak performance. With a focus on quality and safety, we treat every vehicle as if it were our own." },
    { title: "Electrical Repair", text: "Our workshop’s electrical repair services ensure that every circuit and sensor in your vehicle functions flawlessly. We use the latest diagnostic tools alongside our experienced technicians to pinpoint and resolve even the most intricate electrical issues. This commitment to precision not only restores performance but also prevents future malfunctions.<br><br>When it comes to electrical systems, we specialize in troubleshooting and repairing a wide range of issues—from battery failures to advanced sensor diagnostics. Our methodical approach and state-of-the-art techniques ensure that repairs are both reliable and efficient. Trust our expertise to keep your vehicle’s electronics in peak condition." },
    { title: "Bodywork and Paint", text: "Our bodywork and paint services are designed to revitalize your car’s appearance with a flawless finish. We address everything from minor scratches to extensive collision repairs, ensuring each detail is attended to with precision. By using premium materials and modern techniques, we restore both the look and structural integrity of your vehicle.<br><br>Every car deserves to look its best, which is why our specialists focus on blending colors and textures seamlessly to match the original design. We take pride in delivering a high-quality finish that not only enhances aesthetics but also protects your car against future wear. Our meticulous approach ensures that your vehicle leaves our workshop looking as good as new." },
    { title: "Vetted Repairman", text: "Our team of repairmen is rigorously vetted to ensure that only the most skilled professionals work on your vehicle. Each technician undergoes extensive training and certification to meet our high industry standards. This careful selection process guarantees that every repair is performed with utmost expertise and reliability.<br><br>We are committed to excellence by employing repairmen who have a proven track record of quality workmanship and customer satisfaction. Their in-depth knowledge and hands-on experience mean that your car is always in capable, trustworthy hands. With ongoing training and a focus on the latest technologies, our team continually raises the bar in automotive repair." }
];

function changeContent(index) {
    document.getElementById("content-box").innerHTML = `<h2>${content[index].title}</h2><p>${content[index].text}</p>`;
    document.querySelectorAll("button").forEach(btn => btn.classList.remove("active"));
    document.querySelectorAll("button")[index].classList.add("active");
}